const money=n=>new Intl.NumberFormat('fr-BE',{style:'currency',currency:'EUR'}).format(Number(n||0));
const state={view:'tables',tableId:null,category:'Plats',sent:false,dirty:false,payment:'card',tables:[
{id:1,name:'Table 1',seats:2},{id:2,name:'Table 2',seats:4,busy:true},{id:3,name:'Table 3',seats:2},{id:4,name:'Table 4',seats:4},{id:5,name:'Table 5',seats:2},{id:6,name:'Table 6',seats:2,busy:true},{id:7,name:'Table 7',seats:4},{id:8,name:'Table 8',seats:2},{id:9,name:'Table 9',seats:2}],
products:[
{id:1,cat:'Entrées',name:'Croquettes',price:12.9,vat:12,station:'Cuisine'},{id:2,cat:'Entrées',name:'Scampis à l’ail',price:14.5,vat:12,station:'Cuisine'},
{id:3,cat:'Plats',name:'Boulets liégeois',price:19.9,vat:12,station:'Cuisine'},{id:4,cat:'Plats',name:'Carbonnade',price:25.9,vat:12,station:'Cuisine'},{id:5,cat:'Plats',name:'Entrecôte',price:29.9,vat:12,station:'Cuisine'},
{id:6,cat:'Desserts',name:'Café liégeois',price:8.5,vat:12,station:'Dessert'},{id:7,cat:'Desserts',name:'Tiramisu',price:8,vat:12,station:'Dessert'},
{id:8,cat:'Boissons',name:'Coca-Cola',price:3.5,vat:21,station:'Bar'},{id:9,cat:'Boissons',name:'Jupiler',price:3.6,vat:21,station:'Bar'},{id:10,cat:'Boissons',name:'Verre de vin',price:5,vat:21,station:'Bar'}],cart:[]};
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
function toast(m){const t=qs('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function save(){localStorage.setItem('restaurantProDemo',JSON.stringify({tableId:state.tableId,cart:state.cart,sent:state.sent,dirty:state.dirty,payment:state.payment}))}
function load(){try{const d=JSON.parse(localStorage.getItem('restaurantProDemo')||'null');if(d){state.tableId=d.tableId;state.cart=d.cart||[];state.sent=!!d.sent;state.dirty=!!d.dirty;state.payment=d.payment||'card'}}catch{}}
function renderTables(){const w=qs('#tables');w.innerHTML='';state.tables.forEach(t=>{const b=document.createElement('button');b.className='table'+(t.busy?' busy':'')+(state.tableId===t.id?' selected':'');b.innerHTML=`<strong>${t.name}</strong><small>${t.seats} places</small>`;b.onclick=()=>{state.tableId=t.id;state.view='tables';renderTables();renderContext();openSheet();save()};w.appendChild(b)})}
function renderCategories(){const cats=[...new Set(state.products.map(p=>p.cat))],w=qs('#categories');w.innerHTML='';cats.forEach(c=>{const b=document.createElement('button');b.className='category'+(state.category===c?' active':'');b.textContent=c;b.onclick=()=>{state.category=c;renderCategories();renderProducts()};w.appendChild(b)})}
function renderProducts(){const w=qs('#products');w.innerHTML='';state.products.filter(p=>p.cat===state.category).forEach(p=>{const b=document.createElement('button');b.className='product';b.innerHTML=`<strong>${p.name}</strong><div class="meta">${p.station} · TVA ${p.vat}%</div><div class="price">${money(p.price)}</div>`;b.onclick=()=>addProduct(p);w.appendChild(b)})}
function addProduct(p){const e=state.cart.find(i=>i.id===p.id&&!i.separatorAfter);if(e)e.qty++;else state.cart.push({...p,qty:1,separatorAfter:false});state.dirty=true;state.sent=false;renderCart();openSheet();save()}
function changeQty(i,d){i.qty+=d;if(i.qty<=0)state.cart=state.cart.filter(x=>x!==i);state.dirty=true;state.sent=false;renderCart();save()}
function renderCart(){const w=qs('#cart');w.innerHTML='';if(!state.cart.length)w.innerHTML='<div class="empty">Aucun article</div>';state.cart.forEach((i,idx)=>{const d=document.createElement('div');d.className='cart-item';d.innerHTML=`<div class="item-top"><div><b>${i.name}</b><div class="muted">${i.station} · TVA ${i.vat}%</div></div><b>${money(i.price*i.qty)}</b></div><div class="qty"><button class="minus">−</button><b>${i.qty}</b><button class="plus">+</button></div><div class="item-controls"><select class="service"><option>Entrée</option><option>Plat</option><option>Dessert</option><option>Boisson</option></select><button class="separator-btn ${i.separatorAfter?'active':''}">${i.separatorAfter?'✓ Retirer ligne':'➖ Ligne après'}</button></div>`;d.querySelector('.service').value=i.service||({Entrées:'Entrée',Plats:'Plat',Desserts:'Dessert',Boissons:'Boisson'}[i.cat]||'Plat');d.querySelector('.service').onchange=e=>{i.service=e.target.value;state.dirty=true;state.sent=false;save()};d.querySelector('.minus').onclick=()=>changeQty(i,-1);d.querySelector('.plus').onclick=()=>changeQty(i,1);d.querySelector('.separator-btn').onclick=()=>{i.separatorAfter=!i.separatorAfter;state.dirty=true;state.sent=false;renderCart();save()};w.appendChild(d);if(i.separatorAfter&&idx<state.cart.length-1){const s=document.createElement('div');s.className='manual-sep';w.appendChild(s)}});const total=state.cart.reduce((s,i)=>s+i.price*i.qty,0);qs('#subtotal').textContent=money(total);qs('#total').textContent=money(total);qs('#floatingTotal').textContent=money(total);qs('#payBtn').textContent=`PAYER ${money(total)}`;qs('#payBtn').disabled=!state.sent||state.dirty||!state.cart.length;qs('#orderStatus').classList.toggle('hidden',!state.sent);qs('#orderStatus').textContent=state.sent?'✓ Commande envoyée — prête à encaisser':''}
function renderContext(){let txt='Choisissez une table';if(state.view==='takeaway')txt='Commande à emporter';else if(state.view==='delivery')txt='Commande livraison';else if(state.tableId)txt=state.tables.find(t=>t.id===state.tableId)?.name||txt;qs('#context').textContent=txt}
function openSheet(){qs('#cartSheet').classList.add('open')}function closeSheet(){qs('#cartSheet').classList.remove('open')}function modal(t,h){qs('#modalTitle').textContent=t;qs('#modalBody').innerHTML=h;qs('#modal').classList.remove('hidden')}function closeModal(){qs('#modal').classList.add('hidden')}
qsa('.tab').forEach(b=>b.onclick=()=>{qsa('.tab').forEach(x=>x.classList.toggle('active',x===b));state.view=b.dataset.view;if(state.view!=='tables')state.tableId=null;renderContext();if(state.view!=='tables')openSheet();save()});
qs('#openCart').onclick=openSheet;qs('#closeSheet').onclick=closeSheet;qs('#modalClose').onclick=closeModal;qs('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
qs('#sendBtn').onclick=()=>{if(!state.cart.length)return toast('Commande vide');if(state.view==='tables'&&!state.tableId)return toast('Choisissez une table');const g={Cuisine:[],Bar:[],Dessert:[]};state.cart.forEach(i=>g[i.station].push(i));state.sent=true;state.dirty=false;renderCart();save();modal('Commande envoyée',Object.entries(g).filter(([,a])=>a.length).map(([k,a])=>`<div class="ticket"><h4>${k.toUpperCase()}</h4>${a.map(i=>`${i.qty} × ${i.name}${i.separatorAfter?'<div class="sep"></div>':'<br>'}`).join('')}</div>`).join(''));toast('Commande envoyée')};
qs('#splitBtn').onclick=()=>{if(!state.sent||state.dirty)return toast('Envoyez d’abord la commande');const q=state.cart.map(()=>0);modal('Séparer la note',`${state.cart.map((i,idx)=>`<div class="split-row"><div><b>${i.name}</b><div class="muted">${money(i.price)} · dispo ${i.qty}</div></div><div class="split-controls"><button data-i="${idx}" class="sm">−</button><b id="sq${idx}">0</b><button data-i="${idx}" class="sp">+</button></div></div>`).join('')}<div style="display:flex;justify-content:space-between;margin-top:14px"><b>Total</b><b id="splitTotal">0,00 €</b></div>`);const refresh=()=>{let t=0;q.forEach((n,i)=>{qs(`#sq${i}`).textContent=n;t+=n*state.cart[i].price});qs('#splitTotal').textContent=money(t)};qs('#modalBody').onclick=e=>{const i=Number(e.target.dataset.i);if(e.target.classList.contains('sp'))q[i]=Math.min(state.cart[i].qty,q[i]+1);if(e.target.classList.contains('sm'))q[i]=Math.max(0,q[i]-1);refresh()}};
qs('#transferBtn').onclick=()=>{if(state.view!=='tables'||!state.tableId)return toast('Choisissez une table');const free=state.tables.filter(t=>t.id!==state.tableId&&!t.busy);modal('Transférer la table',`<div class="tables">${free.map(t=>`<button class="table transfer" data-id="${t.id}"><strong>${t.name}</strong><small>${t.seats} places</small></button>`).join('')}</div>`);qsa('.transfer').forEach(b=>b.onclick=()=>{state.tableId=Number(b.dataset.id);renderTables();renderContext();closeModal();toast('Table transférée');save()})};
qsa('.pay').forEach(b=>b.onclick=()=>{qsa('.pay').forEach(x=>x.classList.toggle('active',x===b));state.payment=b.dataset.method;save()});
qs('#payBtn').onclick=()=>{if(qs('#payBtn').disabled)return;const total=state.cart.reduce((s,i)=>s+i.price*i.qty,0),vat={6:0,12:0,21:0};state.cart.forEach(i=>{const t=i.price*i.qty;vat[i.vat]+=t-t/(1+i.vat/100)});modal('Ticket client',`<div class="ticket"><h4 style="text-align:center">RESTAURANT PRO</h4><div style="text-align:center">${state.tableId?state.tables.find(t=>t.id===state.tableId)?.name:'Commande'}</div><hr>${state.cart.map(i=>`<div style="display:flex;justify-content:space-between"><span>${i.qty} × ${i.name}</span><b>${money(i.price*i.qty)}</b></div>`).join('')}<hr><div style="display:flex;justify-content:space-between;font-size:18px"><b>TOTAL</b><b>${money(total)}</b></div><hr>${[6,12,21].filter(r=>vat[r]>0).map(r=>`TVA ${r}% : ${money(vat[r])}<br>`).join('')}<br><div style="text-align:center">Merci et à bientôt</div></div>`);if(state.tableId){const t=state.tables.find(x=>x.id===state.tableId);if(t)t.busy=false}state.cart=[];state.sent=false;state.dirty=false;state.tableId=null;renderTables();renderCart();renderContext();save();toast('Paiement enregistré')};
load();renderTables();renderCategories();renderProducts();renderCart();renderContext();
if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}
